import { Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Tumit",
  description: "Generated by tumit",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      < body className={`bg-skew min-h-screen flex flex-col ${playfair.variable} ${roboto.variable}`}>
      
        <header className="p-4 pt-8">
          <Navigation/>
        </header>

        <main>{children}</main>

        <Footer/>

      </body>
    </html>
  );
}